### ISSUE TITLE
Do you really need size_estimate?

### ISSUE THREAD

**Issue by UnixJunkie** [mirage/bloomf#10]
Can't you just memoize how many elements were inserted?
Then, no more an estimate and probably not costly.

**Comment by pascutto** [comment]
Thanks for the suggestion, that would be great to have indeed.
I'm not sure how you would do that though? I don't understand what you mean by memoizing in this context.
When you `add`, how do you know if you're adding a new element - and presumably increment some counter - or just re-adding an element that was already there - and then don't increment the counter?
If you have a solution for this, please feel free to open a PR :)

**Comment by UnixJunkie** [comment]
Ok, this would be in the case you only add distinct elements when constructing the filter.

**Comment by pascutto** [comment]
But you can't ensure that in `bloomf`, so it sounds like it should be implemented externally by you if that's an invariant of your code and not the library.
(Please feel free to reopen the issue if I got it wrong)
